apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: phonestore
type: Opaque
stringData:
  DB_PASSWORD: supersecret
  API_KEY: myapikey123
  DefaultConnection: "Server=mssql-service,1433;Database=PhoneStoreDB;User Id=sa;Password=supersecret;TrustServerCertificate=True"